import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "@/Styles/globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans w-full antialiased p-0 px-4 m-0 sm:grid sm:grid-cols-[1fr,_35rem,_1fr] justify-center items-center text-primary",
          fontSans.variable
        )}
      >
        <div className="w-full sm:col-start-2">{children}</div>
      </body>
    </html>
  );
}
